whoami1:
  image: emilevauge/whoami
  labels:
    - traefik.enable=true
    - traefik.frontend.rule=PathPrefix:/whoami
    - traefik.backend="test"

whoami2:
  image: emilevauge/whoami
  labels:
    - traefik.enable=false