version: '2'

services:

  etcd:
    image: quay.io/coreos/etcd:v3.2.9
    command: /usr/local/bin/etcd --data-dir=/etcd-data --name node1 --initial-advertise-peer-urls http://172.18.0.2:2380 --listen-peer-urls http://172.18.0.2:2380 --advertise-client-urls http://172.18.0.2:2379,http://172.18.0.2:4001 --listen-client-urls http://172.18.0.2:2379,http://172.18.0.2:4001  --initial-cluster node1=http://172.18.0.2:2380 --debug
    expose:
      - 2380
      - 2379
      - 4001
      - 7001
#    networks:
#      etcd_net:
#        ipv4_address: 172.10.1.2

  whoami1:
    image: emilevauge/whoami
    # depends_on option activate because libcompose (used by libkermit) does not support fix IP yet...
    # Remove it ASAP
    depends_on:
      - etcd
#    networks:
#      etcd_net:
#        ipv4_address: 172.10.1.3

  whoami2:
    image: emilevauge/whoami
    # depends_on option activate because libcompose (used by libkermit) does not support fix IP yet...
    # Remove it ASAP
    depends_on:
      - whoami1
#    networks:
#      etcd_net:
#        ipv4_address: 172.10.1.4

  whoami3:
    image: emilevauge/whoami
    # depends_on option activate because libcompose (used by libkermit) does not support fix IP yet...
    # Remove it ASAP
    depends_on:
      - whoami2
#    networks:
#      etcd_net:
#        ipv4_address: 172.10.1.5

  whoami4:
    image: emilevauge/whoami
    # depends_on option activate because libcompose (used by libkermit) does not support fix IP yet...
    # Remove it ASAP
    depends_on:
      - whoami3
#    networks:
#      etcd_net:
#        ipv4_address: 172.10.1.6

#networks:
#  etcd_net:
#    driver: bridge
#    ipam:
#     config:
#       - subnet: 172.10.1.0/28
